// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: learn/simple.proto

package learn

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Learn_Gossip_FullMethodName = "/learn.Learn/Gossip"
)

// LearnClient is the client API for Learn service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LearnClient interface {
	Gossip(ctx context.Context, in *GossipRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Messages], error)
}

type learnClient struct {
	cc grpc.ClientConnInterface
}

func NewLearnClient(cc grpc.ClientConnInterface) LearnClient {
	return &learnClient{cc}
}

func (c *learnClient) Gossip(ctx context.Context, in *GossipRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Messages], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Learn_ServiceDesc.Streams[0], Learn_Gossip_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GossipRequest, Messages]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Learn_GossipClient = grpc.ServerStreamingClient[Messages]

// LearnServer is the server API for Learn service.
// All implementations must embed UnimplementedLearnServer
// for forward compatibility.
type LearnServer interface {
	Gossip(*GossipRequest, grpc.ServerStreamingServer[Messages]) error
	mustEmbedUnimplementedLearnServer()
}

// UnimplementedLearnServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLearnServer struct{}

func (UnimplementedLearnServer) Gossip(*GossipRequest, grpc.ServerStreamingServer[Messages]) error {
	return status.Errorf(codes.Unimplemented, "method Gossip not implemented")
}
func (UnimplementedLearnServer) mustEmbedUnimplementedLearnServer() {}
func (UnimplementedLearnServer) testEmbeddedByValue()               {}

// UnsafeLearnServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LearnServer will
// result in compilation errors.
type UnsafeLearnServer interface {
	mustEmbedUnimplementedLearnServer()
}

func RegisterLearnServer(s grpc.ServiceRegistrar, srv LearnServer) {
	// If the following call pancis, it indicates UnimplementedLearnServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Learn_ServiceDesc, srv)
}

func _Learn_Gossip_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GossipRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LearnServer).Gossip(m, &grpc.GenericServerStream[GossipRequest, Messages]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Learn_GossipServer = grpc.ServerStreamingServer[Messages]

// Learn_ServiceDesc is the grpc.ServiceDesc for Learn service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Learn_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "learn.Learn",
	HandlerType: (*LearnServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Gossip",
			Handler:       _Learn_Gossip_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "learn/simple.proto",
}
